SAMPLES: KIRC,HNSCC,PDA,CCRCC,NSCLC,OCTANE
datasets:
  NSCLC: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/NSCLC_filtered_TPM.csv"
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/HNSCC_filtered_TPM.csv"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/PDA_filtered_TPM.csv"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/CCRCC_filtered_TPM.csv"
  KIRC: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/KIRC_filtered_TPM.csv"
  OCTANE: "/cluster/projects/bhklab/rawdata/Radiogenomics/TPM_RNAseq_data/OCTANE_filtered_TPM.csv"

patient_ids:
  NSCLC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/NSCLC_patientids.txt"
  HNSCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_HNSCC_patientids.txt"
  PDA: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_PDA_patientids.txt"
  CCRCC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/CPTAC_CCRCC_patientids.txt"
  KIRC: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/TCGA_KIRC_patientids.txt"
  OCTANE: "/cluster/projects/bhklab/rawdata/Radiogenomics/sample_ids/OCTANE_patientids.txt"
# Add GMT file paths for each gene set collection
hallmark_gmt: "/cluster/projects/bhklab/rawdata/Radiogenomics/gmt/h.all.v2025.1.Hs.symbols.gmt"
