# Config file for TCIA_TCGA-KIRC
dataset_name: TCIA_TCGA-KIRC

# String pattern of patient ID for this dataset -
# Matches IDs like: TCGA-B0-5115, TCGA-BP-4345, TCGA-B8-5165
# Pattern: TCGA-<2 alphanumeric>-<4 alphanumeric>
patient_id_pattern: "^TCGA-[A-Za-z0-9]{2}-[A-Za-z0-9]{4}$"


# Med-ImageTools arguments
# General name of region of interest and all possible ROI name matches in the dataset / regex to match all possible ROI name matches
roi_pattern: {GTV: "_.*"}

# Modalities present in the dataset to process
modalities: "CT,SEG"

# READII arguments
# Region of image to apply negative control strategy to
negative_control_regions: ["full", "roi", "non_roi"]
# Which negative control strategies to apply
negative_control_types: ["shuffled", "randomized", "randomized_sampled"]

# Method to use to crop images to expected input size for FMCIB inference
crop_method: "cube" 
# crop_method options:
# 1. `bbox` - Find bounding box based on dimensions of the region of interest (ROI), crop image to these coordinates, resize/resample to `FMCIB_INPUT_SIZE`.
# 2. `cube` - Create cube based on largest ROI bounding box dimension, crop image to these coordinates, resize/resample to `FMCIB_INPUT_SIZE`.
# 3. `centroid` - Create `FMCIB_INPUT_SIZE` cube centered on the ROI centroid, crop to these coordinates.

# Size to crop/resize images to for FMCIB inference 
crop_size: [50, 50, 50]